#!/usr/bin/env bash

make O=out ARCH=arm64 vayu_defconfig
make O=out ARCH=arm64 menuconfig
make O=out ARCH=arm64 savedefconfig

cp out/defconfig arch/arm64/configs/vayu_defconfig

if [ ! -z $@ ]; then
  git commit -asm "configs: vayu: Regenerate"
fi
